media:
  input: public
  output: /files/media

content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    fields:
      # ... fields defined here ...
  - name: authors
    label: Authors
    path: src/_data/authors.json
    type: file
    fields:

components:
  hero: # 'hero' is the component name/key
    label: Hero Section
    type: object
    fields:
      - name: headline
        label: Headline
        type: text
        required: true
      - name: cover
        label: Cover Image
        type: image
  email: # 'email' is the component name/key
    label: Email Address
    type: string
    pattern:
      regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      message: 'This must be a valid email address (e.g. hello@example.com).'