media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: tag
        label: Tag
        type: select
        options:
          values: [ Tech, News, Sports ]
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text